POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "fullName": "Dat Pham",
    "username": "datpham0412",
    "email": "tiendat041202@gmail.com",
    "password": "datdat123123"
}
